
peers:
  -
    tls: true
    # event_url: 'grpc://localhost:7053'
    # tls使用 grpcs://localhost:7051 非tls使用grpc://localhost:7051   tls:grpcs / 非tls:grpc
    host: 'grpc://localhost:7051' 
    peer_url: '/localhost:7051'
    # tls 必须使用域名
    hostname: peer0.org1.example.com
    tls_cacerts : '/home/zh/fabric1.1/deploy/e2ecli/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt'
  # - 
  #   tls: true
  #   host: 'grpc://localhost:9051'
  #   peer_url: 'localhost:9051'
  #   hostname: peer0.org2.example.com
  #   tls_cacerts: '/home/zh/fabric1.1/deploy/e2ecli/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt'
  
orderer:
    host: 'grpc://localhost:7050'
    hostname: 'orderer.example.com'
    tls_cacerts: '/home/zh/fabric1.1/deploy/e2ecli/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt'
  

channel:
  channel_id: mychannel
  chaincode_id: mycc

user:
  user_id: Admin@org1.example.com
  msp_id: Org1MSP
  privateKeyFolder: '/home/zh/fabric1.1/deploy/e2ecli/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore'
  signedCert: '/home/zh/fabric1.1/deploy/e2ecli/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem'
    